const actionTypes = {
//DEPRECATED
// FILTER_POSTS: "FILTER_POSTS",

//AUTH
LOGIN: "LOGIN",
REGISTER: "REGISTER",
LOGOUT: "LOGOUT",
GET_USER: "GET_USER",
AUTHENTICATION: "AUTHENTICATION",

//POSTS
GET_POSTS: "GET_POSTS",
GET_POST: "GET_POST",
POST_POST: "POST_POST",
PUT_POST: "PUT_POST",
DELETE_POST: "DELETE_POST",

//STATUS
PENDING: "_PENDING",
FULFILLED: "_FULFILLED",
REJECTED: "_REJECTED",
}

export default actionTypes