DROP TABLE IF EXISTS users;
CREATE TABLE users
(id SERIAL PRIMARY KEY,
username VARCHAR(120),
hash VARCHAR(1000),
img VARCHAR(1000));
SELECT * FROM users;

ALTER TABLE users
ALTER hash
SET DATA TYPE VARCHAR(2000);
SELECT * FROM users;

DROP TABLE IF EXISTS posts;
CREATE TABLE posts
(id SERIAL PRIMARY KEY,
author_id INTEGER REFERENCES users(id),
title VARCHAR(120),
img VARCHAR(1000),
content VARCHAR(2500));
SELECT * FROM posts;